### ISSUE TITLE
Question about a lost repo

### ISSUE THREAD

**Issue by veso266** [kingofnull/SSR-URL-to-config#1]
Hello there, I don't know how to contact you so I have opened an issue

Back in 2017 you forked 2 repositories: 
https://github.com/kingofnull/ali3602
https://github.com/kingofnull/ali3606

they were unfortionatly taken down by DMCA

I was just wondering if you maybe managed to save them somewhere and still have them and could maybe put it on mediafire or somewhere else?

Thanks for Anwsering and Best Regards

**Comment by kingofnull** [comment]
I found ali3602 repo and upload it for you I hope it could help you:

https://www.mediafire.com/file/s7bfdep27pjsjyn/ali3602-master.7z/file

**Comment by kingofnull** [comment]
> Hello there, I don't know how to contact you so I have opened an issue
> 
> Back in 2017 you forked 2 repositories: https://github.com/kingofnull/ali3602 https://github.com/kingofnull/ali3606
> 
> they were unfortionatly taken down by DMCA
> 
> I was just wondering if you maybe managed to save them somewhere and still have them and could maybe put it on mediafire or somewhere else?
> 
> Thanks for Anwsering and Best Regards

I found ali3602 repo and uploaded it for you I hope it could help you:

https://www.mediafire.com/file/s7bfdep27pjsjyn/ali3602-master.7z/file

**Comment by veso266** [comment]
Wow, thanks man, I was afraid all this is lost forever

Realy not sure where all this originated from but kudos to the first person that shared that and kudos to you for preserving this

now I only need to find the SDK for the ali3606 chip and recent source code for AliEditor and I can finaly modify the fw on my STB receiver

**Comment by openshwprojects** [comment]
Hey! Do anyone still have this SDK? openshwprojects@gmail.com thanks!

**Comment by veso266** [comment]
OF course I do (sent u email)
