### ISSUE TITLE
would be super awesome to support VLESS/Hysteria too

### ISSUE THREAD

**Issue by hadifarnoud** [kingofnull/SSR-URL-to-config#2]
In my situation, I have to change my servers every day and doing that by hand is hard. I need a tool like this but this does not support VLESS

**Comment by freeiance** [comment]
You can use this [V2rey to clash config](https://v2rayse.com/en/v2ray-clash/) . I also will add vmess support very soon.

**Comment by kingofnull** [comment]
It does support VLESS/HTTP/SS/SSR. I recently fixed a bug related to VLESS conversion with http header as well. If you have a problem with VLESS, provide example a VLESS url and equivalent valid config for Clash.

About Hysteria I never heard about that. Also based on Clash config there is no support for Hysteria in Clash core. If you have any reference about it you may mention it.

Don't forget to star this repo!

**Comment by hadifarnoud** [comment]
Thank you 🙏🏻
Hysteria is supported in Clash Meta core, just like VLESS.

I don't use it much tbh. I mostly use VLESS

**Comment by hadifarnoud** [comment]
I just tried it, still does not work with VLESS URI. would you add trojan support too?

**Comment by kingofnull** [comment]
> I just tried it, still does not work with VLESS URI. would you add trojan support too?

Can you provide your source URI?

If you are in hurry you can use this tool : https://v2rayse.com/en/v2ray-clash

**Comment by kingofnull** [comment]
I ripped main JS functions from  v2ray-clash but I don't like to use them in project. You can use them in your setup. His implementation is very comprehensive and support almost all the available format. 

[uri2clash_2.zip](https://github.com/kingofnull/SSR-URL-to-config/files/10436052/uri2clash_2.zip)

**Comment by hadifarnoud** [comment]
Thank you. I did try that and it works great for VLESS. However, shadowsocks and VMESS does not work

```
node uri2clash.js -c vmess://eyJhZGQiOiJqZ*****
/Users/hadifarnoud/.config/clash/v2ray_bot/uri2clash.js:205
        : e.startsWith("vmess://")
            ^

ReferenceError: m is not defined
    at convert (/Users/hadifarnoud/.config/clash/v2ray_bot/uri2clash.js:205:13)
    at uri2Clash (/Users/hadifarnoud/.config/clash/v2ray_bot/uri2clash.js:439:10)
    at Object.<anonymous> (/Users/hadifarnoud/.config/clash/v2ray_bot/uri2clash.js:443:3)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
```

```
node uri2clash.js -c ss://*****

/Users/hadifarnoud/.config/clash/v2ray_bot/uri2clash.js:181
                var O = Object(o.a)(subBefore(n, "@", !1)),
                               ^

ReferenceError: o is not defined
    at /Users/hadifarnoud/.config/clash/v2ray_bot/uri2clash.js:181:32
    at convert (/Users/hadifarnoud/.config/clash/v2ray_bot/uri2clash.js:204:13)
    at uri2Clash (/Users/hadifarnoud/.config/clash/v2ray_bot/uri2clash.js:439:10)
    at Object.<anonymous> (/Users/hadifarnoud/.config/clash/v2ray_bot/uri2clash.js:443:3)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
```

it's even more helpful that you gave me a js file. I can do all sorts of automation this way. I could not find the original code in the above site in order to complete this file.

I'd appreciate it if you also add these two missing functions as well 🙏🏻

**Comment by kingofnull** [comment]
Oh no I should tested all the types 😅. I'll fix that. Anyway if you have shell access ; I strongly recommend [subconverter ](https://github.com/tindy2013/subconverter) . It's very major , well maintained and support all available profile sources , merge and more.

### Ping and test
For profile pinging and testing, There are relatively good solutions too:

https://github.com/xxf098/LiteSpeedTest

https://github.com/tindy2013/stairspeedtest-reborn

### Complete solutions

These guys done a complete setup for collecting and testing base on GitHub actions and workflows:

https://github.com/aiirobyte/TopFreeProxies

https://github.com/mahdibland/V2RayAggregator

**Comment by kingofnull** [comment]
> Thank you. I did try that and it works great for VLESS. However, shadowsocks and VMESS does not work
> 
> ```
> node uri2clash.js -c vmess://eyJhZGQiOiJqZ*****
> /Users/hadifarnoud/.config/clash/v2ray_bot/uri2clash.js:205
>         : e.startsWith("vmess://")
>             ^
> 
> ReferenceError: m is not defined
>     at convert (/Users/hadifarnoud/.config/clash/v2ray_bot/uri2clash.js:205:13)
>     at uri2Clash (/Users/hadifarnoud/.config/clash/v2ray_bot/uri2clash.js:439:10)
>     at Object.<anonymous> (/Users/hadifarnoud/.config/clash/v2ray_bot/uri2clash.js:443:3)
>     at Module._compile (internal/modules/cjs/loader.js:1072:14)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
>     at Module.load (internal/modules/cjs/loader.js:937:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
>     at internal/main/run_main_module.js:17:47
> ```
> 
> ```
> node uri2clash.js -c ss://*****
> 
> /Users/hadifarnoud/.config/clash/v2ray_bot/uri2clash.js:181
>                 var O = Object(o.a)(subBefore(n, "@", !1)),
>                                ^
> 
> ReferenceError: o is not defined
>     at /Users/hadifarnoud/.config/clash/v2ray_bot/uri2clash.js:181:32
>     at convert (/Users/hadifarnoud/.config/clash/v2ray_bot/uri2clash.js:204:13)
>     at uri2Clash (/Users/hadifarnoud/.config/clash/v2ray_bot/uri2clash.js:439:10)
>     at Object.<anonymous> (/Users/hadifarnoud/.config/clash/v2ray_bot/uri2clash.js:443:3)
>     at Module._compile (internal/modules/cjs/loader.js:1072:14)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
>     at Module.load (internal/modules/cjs/loader.js:937:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
>     at internal/main/run_main_module.js:17:47
> ```

> 
> it's even more helpful that you gave me a js file. I can do all sorts of automation this way. I could not find the original code in the above site in order to complete this file.
> 
> I'd appreciate it if you also add these two missing functions as well 🙏🏻

I believe the issue should be fixed. I tested one of any type and three types for vmess. Try new file.

[uri2clash.zip](https://github.com/kingofnull/SSR-URL-to-config/files/10458906/uri2clash.zip)

**Comment by hadifarnoud** [comment]
Thank you so much. I am creating a bot to collect v2ray servers, then it tests them, and finally, it will automatically create a proxy config for clash.

you don't have to think about it anymore. it just works :)
I'll share the code when done. if interested, send me an email at hadi.farnoud gmail.

**Comment by kingofnull** [comment]
> Thank you so much. I am creating a bot to collect v2ray servers, then it tests them, and finally, it will automatically create a proxy config for clash.
> 
> you don't have to think about it anymore. it just works :) I'll share the code when done. if interested, send me an email at hadi.farnoud gmail.

I really interested about where you get free proxy's profiles. Please contact me at (kingofnull.github gmail).
After more testing (about 4000 profiles) , I fix some bugs related to Base64 decode with unicode characters. I share final code which should be run using nodejs like this `node uri2clash.js -i test.txt -o test.yaml` . I hope, will be helpful to you.

[clash-config-converter.zip](https://github.com/kingofnull/SSR-URL-to-config/files/10472487/clash-config-converter.zip)
